# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50e5ea04124df72d2d2c0261dba7a129f2e370b9f17da830c3f34cfb2e872e91d14332a8be8ad0fa87cb8b449cd47ec4ed7ac279a86a54d7292400c64d6480d

test:
  secret_key_base: c8507d5a5cd0cab874a2433f9432ad566238fce5a4209628d7a979a01aac4ea4b610d95e11db44e33c917402f767e9ce8470942e71b2d38fba910d46df6dad28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
